export const HartronAdvanceSkillCenter= [
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "AI - Database Administrator",
        description: "A Data Analyst collects, cleans, and interprets data, using tools like Excel, SQL, and Tableau to analyze trends and provide insights for decisions.",
        likes: "analyzing data to find insights, creating reports and visualizations, working with spreadsheets and databases",
        salary: "$289,008",
        jobs: "23,498",
        credentials: [
        "IBM Data Analyst",
        "DeepLearning AI Data Analytics",
        "+ 5 more"
        ],
        Duration_hours: "450",
        NSQF: "5.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "AI Data Scientist",
        description: "An AI Data Scientist develops machine learning models and algorithms to extract insights from complex datasets, driving business decisions and innovation.",
        likes: "working with large datasets, developing predictive models, solving complex problems with AI",
        salary: "$312,450",
        jobs: "18,742",
        credentials: [
        "IBM AI Engineering",
        "DeepLearning AI TensorFlow Developer",
        "+ 4 more"
        ],
        Duration_hours: "690",
        NSQF: "6.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Artificial Intelligence Application Developer",
        description: "Develops AI-powered applications and systems that can perform tasks typically requiring human intelligence, such as visual perception and decision-making.",
        likes: "programming AI solutions, integrating AI into applications, working with neural networks",
        salary: "$298,760",
        jobs: "15,329",
        credentials: [
        "Microsoft AI Engineer",
        "Google Professional ML Engineer",
        "+ 3 more"
        ],
        Duration_hours: "540",
        NSQF: "4.5",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Artificial Intelligence Associate",
        description: "Entry-level AI professional assisting in developing and implementing AI solutions, with foundational knowledge of machine learning and data processing.",
        likes: "learning AI concepts, assisting in AI projects, working with data preprocessing",
        salary: "$245,300",
        jobs: "27,891",
        credentials: [
        "IBM Applied AI Professional",
        "Google AI Fundamentals",
        "+ 2 more"
        ],
        Duration_hours: "450",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Cyber Secured Web Development Associate",
        description: "Develops secure web applications with knowledge of cybersecurity principles to protect against vulnerabilities and attacks.",
        likes: "building secure websites, implementing security protocols, coding with protection in mind",
        salary: "$278,940",
        jobs: "19,456",
        credentials: [
        "Certified Secure Web Application Developer",
        "OWASP Security Certification",
        "+ 4 more"
        ],
        Duration_hours: "990",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Cyber Security and Social Media Analyst",
        description: "Monitors and analyzes social media platforms for security threats, protecting organizations from digital risks and reputation damage.",
        likes: "tracking online threats, analyzing social media patterns, implementing security measures",
        salary: "$265,800",
        jobs: "14,237",
        credentials: [
        "Certified Social Media Security Professional",
        "EC-Council Social Media Investigator",
        "+ 3 more"
        ],
        Duration_hours: "480",
        NSQF: "5.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Cyber Security Associate",
        description: "Entry-level cybersecurity professional assisting in protecting systems and networks from digital attacks and unauthorized access.",
        likes: "learning security protocols, monitoring systems for threats, assisting in vulnerability assessments",
        salary: "$255,600",
        jobs: "32,189",
        credentials: [
        "CompTIA Security+",
        "EC-Council Certified Security Analyst",
        "+ 2 more"
        ],
        Duration_hours: "540",
        NSQF: "4.5",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Data Analysis Associate",
        description: "Assists in collecting, processing, and performing statistical analyses on datasets to help organizations make data-driven decisions.",
        likes: "working with data visualization tools, cleaning datasets, creating basic reports",
        salary: "$235,400",
        jobs: "28,745",
        credentials: [
        "Google Data Analytics Certificate",
        "Microsoft Data Analyst Associate",
        "+ 2 more"
        ],
        Duration_hours: "450",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Internet of Things (IoT) Associate",
        description: "Works with IoT devices and systems, assisting in connecting physical devices to networks and analyzing sensor data.",
        likes: "working with smart devices, connecting hardware to software, analyzing sensor data",
        salary: "$248,900",
        jobs: "16,832",
        credentials: [
        "Certified IoT Practitioner",
        "Microsoft Azure IoT Developer",
        "+ 2 more"
        ],
        Duration_hours: "450",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "IoT - Software Analyst",
        description: "Analyzes and develops software solutions for IoT systems, ensuring seamless communication between devices and platforms.",
        likes: "developing IoT applications, analyzing system requirements, optimizing device communication",
        salary: "$285,700",
        jobs: "12,943",
        credentials: [
        "AWS Certified IoT Specialty",
        "Google Cloud Professional IoT Engineer",
        "+ 3 more"
        ],
        Duration_hours: "690",
        NSQF: "5.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Junior Cloud Computing Associate",
        description: "Entry-level professional assisting in cloud-based solutions, learning to deploy and manage applications in cloud environments.",
        likes: "working with cloud platforms, learning deployment strategies, assisting in cloud migrations",
        salary: "$240,500",
        jobs: "25,671",
        credentials: [
        "AWS Cloud Practitioner",
        "Microsoft Azure Fundamentals",
        "+ 2 more"
        ],
        Duration_hours: "450",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Junior Cyber Security Associate",
        description: "Begins career in cybersecurity, learning fundamental security concepts and assisting in basic protection measures.",
        likes: "learning about cyber threats, assisting in security monitoring, understanding security frameworks",
        salary: "$238,900",
        jobs: "29,456",
        credentials: [
        "ISC2 Certified in Cybersecurity",
        "CompTIA IT Fundamentals+",
        "+ 1 more"
        ],
        Duration_hours: "450",
        NSQF: "4.0",
        category: "Hartron Advance Skill Center"
    },
    {
        img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
        title: "Junior Data Analyst",
        description: "Entry-level position assisting senior analysts in collecting, cleaning, and interpreting data to support business decisions.",
        likes: "working with spreadsheets, learning data visualization, assisting in report generation",
        salary: "$230,800",
        jobs: "31,289",
        credentials: [
        "Tableau Desktop Specialist",
        "Microsoft Power BI Data Analyst",
        "+ 2 more"
        ],
        Duration_hours: "540",
        NSQF: "4.5",
        category: "Hartron Advance Skill Center"
    }
    ];  

 export const HartronSkillCenter = [
  {
    id: "HSC-001",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COMPUTER HARDWARE AND NETWORKING ASSOCIATE',
    description: "Professional training in computer assembly, networking fundamentals, and hardware troubleshooting. Gain hands-on experience with routers, switches, and system maintenance.",
    likes: "assembling computers, configuring networks, solving technical issues",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Hardware',
    skills: ['PC Assembly', 'Network Configuration', 'Troubleshooting', 'OS Installation'],
    certification: 'Hartron Certified Hardware Technician',
    careerPaths: ['Hardware Technician', 'Network Support Specialist', 'IT Support Engineer'],
    fee: '₹25,000',
    eligibility: '10th Pass'
  },
  {
    id: "HSC-002",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN COMPUTER APPLICATION',
    description: "Comprehensive training in office productivity tools including advanced Excel, Word processing, presentation software, and internet applications for professional environments.",
    likes: "creating documents, analyzing data, making presentations",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Software',
    skills: ['MS Office', 'Email Communication', 'Internet Research', 'File Management'],
    certification: 'Hartron Office Specialist',
    careerPaths: ['Office Assistant', 'Data Entry Operator', 'Administrative Support'],
    fee: '₹18,000',
    eligibility: '10th Pass'
  },
  {
    id: "HSC-003",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN DIGITAL ACCOUNTING',
    description: "Master computerized accounting with Tally Prime, GST filing, payroll management, and financial reporting for modern business accounting needs.",
    likes: "working with numbers, financial calculations, using accounting software",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Finance',
    skills: ['Tally ERP', 'Financial Reporting', 'GST Filing', 'Bookkeeping'],
    certification: 'Hartron Accounting Professional',
    careerPaths: ['Account Assistant', 'Bookkeeper', 'Billing Executive'],
    fee: '₹22,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-004",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN DESIGNING AND PUBLISHING',
    description: "Professional graphic design training covering Adobe Creative Suite (Photoshop, Illustrator, InDesign) for print and digital media publishing.",
    likes: "creating visual designs, working with colors, expressing creativity",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Design',
    skills: ['Adobe Photoshop', 'Illustrator', 'Layout Design', 'Print Media'],
    certification: 'Hartron Certified Designer',
    careerPaths: ['Graphic Designer', 'Desktop Publisher', 'Visual Content Creator'],
    fee: '₹28,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-005",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN WEB TECHNOLOGY',
    description: "Full-stack web development course covering HTML5, CSS3, JavaScript, and CMS platforms for building responsive and interactive websites.",
    likes: "coding websites, solving design challenges, creating user interfaces",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Development',
    skills: ['HTML5', 'CSS3', 'JavaScript', 'WordPress'],
    certification: 'Hartron Web Developer',
    careerPaths: ['Web Designer', 'Front-end Developer', 'UI Developer'],
    fee: '₹30,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-006",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN SOFTWARE DEVELOPMENT',
    description: "Fundamentals of software engineering covering programming logic, algorithms, and application development using modern development tools.",
    likes: "solving problems with code, building applications, logical thinking",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Development',
    skills: ['Programming Basics', 'Algorithm Design', 'Debugging', 'SDLC'],
    certification: 'Hartron Software Developer',
    careerPaths: ['Junior Programmer', 'Software Trainee', 'Application Developer'],
    fee: '₹32,000',
    eligibility: '12th Pass with Mathematics'
  },
  {
    id: "HSC-007",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'ADVANCED COURSE IN COMPUTER APPLICATION',
    description: "Advanced training in computer applications including database management, advanced Excel macros, and professional presentation techniques.",
    likes: "data analysis, automating tasks, creating dashboards",
    duration: '52 Weeks',
    durationType: 'Long Duration',
    category: 'Software',
    skills: ['Advanced Excel', 'Database Management', 'PowerPoint', 'Data Analysis'],
    certification: 'Hartron Advanced Computing Specialist',
    careerPaths: ['Office Administrator', 'Executive Assistant', 'Data Analyst'],
    fee: '₹24,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-008",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'DIGITAL MARKETING ASSISTANT',
    description: "Comprehensive digital marketing training covering SEO, SEM, social media marketing, email marketing, and content strategy for online businesses.",
    likes: "creating campaigns, analyzing metrics, engaging audiences",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Marketing',
    skills: ['SEO', 'Social Media', 'Content Marketing', 'Google Analytics'],
    certification: 'Hartron Digital Marketing Professional',
    careerPaths: ['Digital Marketing Executive', 'Social Media Manager', 'SEO Specialist'],
    fee: '₹20,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-009",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'SOFTWARE OR APPLICATION TESTING ASSISTANT',
    description: "Professional software testing training covering manual testing, test case development, bug tracking, and quality assurance methodologies.",
    likes: "finding bugs, ensuring quality, documenting issues",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Testing',
    skills: ['Manual Testing', 'Test Cases', 'Bug Tracking', 'Quality Assurance'],
    certification: 'Hartron QA Tester',
    careerPaths: ['QA Tester', 'Test Engineer', 'Quality Analyst'],
    fee: '₹22,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-010",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'ASSISTANT PHP DEVELOPER',
    description: "Server-side web development using PHP with MySQL database integration, covering form handling, sessions, and basic CMS development.",
    likes: "building web applications, database programming, solving backend challenges",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Development',
    skills: ['PHP Basics', 'MySQL', 'Form Handling', 'CMS Basics'],
    certification: 'Hartron PHP Developer',
    careerPaths: ['PHP Developer', 'Web Application Developer', 'Backend Trainee'],
    fee: '₹25,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-011",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'HARDWARE PERIPHERAL AND INSTALLATION ASSISTANT',
    description: "Specialized training in computer peripherals installation, maintenance, and troubleshooting for printers, scanners, and other devices.",
    likes: "working with hardware, solving installation issues, technical maintenance",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Hardware',
    skills: ['Printer Maintenance', 'Device Installation', 'Driver Configuration', 'Troubleshooting'],
    certification: 'Hartron Peripheral Technician',
    careerPaths: ['Hardware Support', 'IT Technician', 'Field Service Engineer'],
    fee: '₹20,000',
    eligibility: '10th Pass'
  },
  {
    id: "HSC-012",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'APPLICATION DEVELOPMENT - ANDROID',
    description: "Mobile app development for Android platform using Java/Kotlin, covering UI design, database integration, and Play Store deployment.",
    likes: "building mobile apps, solving UX challenges, publishing applications",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Development',
    skills: ['Android Studio', 'Java/Kotlin', 'Mobile UI', 'Play Store Deployment'],
    certification: 'Hartron Android Developer',
    careerPaths: ['Mobile App Developer', 'Android Engineer', 'Freelance Developer'],
    fee: '₹28,000',
    eligibility: '12th Pass with Programming Knowledge'
  },
  {
    id: "HSC-013",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'COURSE IN IT FOUNDATION AND TOOLS',
    description: "Fundamental IT skills training covering computer basics, internet technologies, and essential productivity tools for beginners.",
    likes: "learning tech basics, improving digital literacy, mastering essential tools",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Foundation',
    skills: ['Computer Basics', 'Internet Usage', 'Productivity Tools', 'File Management'],
    certification: 'Hartron IT Fundamentals',
    careerPaths: ['Computer Operator', 'Data Entry Specialist', 'Office Assistant'],
    fee: '₹15,000',
    eligibility: '10th Pass'
  },
  {
    id: "HSC-014",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'CERTIFICATE COURSE IN COMPUTER BASICS & ACCOUNTING',
    description: "Combined course covering computer fundamentals along with basic accounting principles and computerized accounting practices.",
    likes: "working with numbers, learning accounting software, mastering spreadsheets",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Finance',
    skills: ['Basic Accounting', 'Tally', 'Excel for Accounting', 'Financial Records'],
    certification: 'Hartron Accounting Assistant',
    careerPaths: ['Accounts Assistant', 'Billing Clerk', 'Bookkeeping Assistant'],
    fee: '₹18,000',
    eligibility: '10th Pass'
  },
  {
    id: "HSC-015",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'CERTIFICATE COURSE IN WEB DESIGNING AND MULTIMEDIA',
    description: "Creative web design training covering HTML, CSS, JavaScript along with multimedia tools for interactive web content creation.",
    likes: "designing websites, creating visual content, coding interfaces",
    duration: '26 Weeks',
    durationType: 'Medium Duration',
    category: 'Design',
    skills: ['Web Design', 'Multimedia Tools', 'Basic Animation', 'UI Principles'],
    certification: 'Hartron Web Designer',
    careerPaths: ['Web Designer', 'UI Developer', 'Multimedia Specialist'],
    fee: '₹22,000',
    eligibility: '12th Pass'
  },
  {
    id: "HSC-016",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'C LANGUAGE',
    description: "Fundamentals of C programming covering syntax, data structures, algorithms, and problem-solving techniques for beginners.",
    likes: "logical problem solving, understanding programming concepts, algorithm development",
    duration: '4 Weeks',
    durationType: 'Short Duration',
    category: 'Programming',
    skills: ['C Syntax', 'Data Structures', 'Algorithms', 'Problem Solving'],
    certification: 'Hartron C Programmer',
    careerPaths: ['Software Trainee', 'Embedded Systems Programmer', 'Academic Projects'],
    fee: '₹5,000',
    eligibility: '12th Pass with Mathematics'
  },
  {
    id: "HSC-017",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'C PLUS PLUS WITH OOPS',
    description: "Object-oriented programming with C++ covering classes, objects, inheritance, polymorphism, and advanced data structures.",
    likes: "object-oriented design, solving complex problems, game programming basics",
    duration: '8 Weeks',
    durationType: 'Short Duration',
    category: 'Programming',
    skills: ['OOP Concepts', 'C++ Syntax', 'Data Structures', 'Memory Management'],
    certification: 'Hartron C++ Developer',
    careerPaths: ['Software Developer', 'Game Programmer', 'System Programmer'],
    fee: '₹8,000',
    eligibility: 'Knowledge of C Programming'
  },
  {
    id: "HSC-018",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'PHP WITH MYSQL',
    description: "Web development with PHP and MySQL covering form processing, sessions, cookies, and database-driven web applications.",
    likes: "building dynamic websites, database integration, server-side scripting",
    duration: '4 Weeks',
    durationType: 'Short Duration',
    category: 'Development',
    skills: ['PHP Programming', 'MySQL Queries', 'Form Handling', 'Basic Security'],
    certification: 'Hartron PHP Programmer',
    careerPaths: ['Web Developer', 'Backend Programmer', 'CMS Developer'],
    fee: '₹6,000',
    eligibility: 'Basic HTML Knowledge'
  },
  {
    id: "HSC-019",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'CORE JAVA',
    description: "Java programming fundamentals covering syntax, OOP concepts, exception handling, and basic application development.",
    likes: "cross-platform development, object-oriented programming, building applications",
    duration: '6 Weeks',
    durationType: 'Short Duration',
    category: 'Programming',
    skills: ['Java Syntax', 'OOP Principles', 'Exception Handling', 'Collections'],
    certification: 'Hartron Java Programmer',
    careerPaths: ['Java Developer', 'Android App Developer', 'Software Engineer'],
    fee: '₹7,000',
    eligibility: 'Programming Fundamentals'
  },
  {
    id: "HSC-020",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'ADVANCE JAVA',
    description: "Advanced Java programming covering JDBC, Servlets, JSP, and web application development for enterprise solutions.",
    likes: "web application development, database connectivity, enterprise solutions",
    duration: '8 Weeks',
    durationType: 'Short Duration',
    category: 'Programming',
    skills: ['JDBC', 'Servlets', 'JSP', 'Web Applications'],
    certification: 'Hartron Advanced Java Developer',
    careerPaths: ['J2EE Developer', 'Web Application Developer', 'Enterprise Programmer'],
    fee: '₹9,000',
    eligibility: 'Core Java Knowledge'
  },
  {
    id: "HSC-021",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'FINANCIAL ACCOUNTING',
    description: "Professional financial accounting course covering accounting principles, financial statements, taxation basics, and accounting software.",
    likes: "working with financial data, understanding business finance, accounting principles",
    duration: '6 Weeks',
    durationType: 'Short Duration',
    category: 'Finance',
    skills: ['Financial Statements', 'Taxation Basics', 'Accounting Principles', 'Tally'],
    certification: 'Hartron Accounting Professional',
    careerPaths: ['Accountant', 'Financial Assistant', 'Tax Preparer'],
    fee: '₹6,500',
    eligibility: '12th Pass Commerce Preferred'
  },
  {
    id: "HSC-022",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'AUTOCAD',
    description: "Professional 2D and 3D drafting using AutoCAD for engineering drawings, architectural plans, and technical designs.",
    likes: "creating technical drawings, engineering designs, architectural drafting",
    duration: '8 Weeks',
    durationType: 'Short Duration',
    category: 'Design',
    skills: ['2D Drafting', '3D Modeling', 'Technical Drawing', 'CAD Principles'],
    certification: 'Hartron AutoCAD Professional',
    careerPaths: ['CAD Technician', 'Drafting Engineer', 'Architectural Assistant'],
    fee: '₹10,000',
    eligibility: 'Diploma/Degree in Engineering or Architecture'
  },
  {
    id: "HSC-023",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'FUNDAMENTALS OF CYBER SECURITY',
    description: "Introduction to cybersecurity concepts covering threats, vulnerabilities, encryption, and basic security practices for IT systems.",
    likes: "understanding security threats, protecting systems, ethical hacking basics",
    duration: '6 Weeks',
    durationType: 'Short Duration',
    category: 'Security',
    skills: ['Security Principles', 'Threat Analysis', 'Basic Cryptography', 'Security Practices'],
    certification: 'Hartron Cyber Security Associate',
    careerPaths: ['Security Analyst', 'Network Administrator', 'IT Security Specialist'],
    fee: '₹8,000',
    eligibility: 'Basic Computer Knowledge'
  },
  {
    id: "HSC-024",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'PROGRAMMING WITH PYTHON',
    description: "Python programming fundamentals covering syntax, data structures, file handling, and basic application development.",
    likes: "writing clean code, data analysis basics, automating tasks",
    duration: '12 Weeks',
    durationType: 'Short Duration',
    category: 'Programming',
    skills: ['Python Syntax', 'Data Structures', 'File Handling', 'Basic Algorithms'],
    certification: 'Hartron Python Programmer',
    careerPaths: ['Python Developer', 'Data Analyst', 'Automation Engineer'],
    fee: '₹9,500',
    eligibility: 'Basic Programming Knowledge'
  },
  {
    id: "HSC-025",
    img: 'https://res.cloudinary.com/dnpn8ljki/image/upload/v1749706316/full_stack_tfxslb.avif',
    title: 'FUNDAMENTALS OF COMPUTER',
    description: "Basic computer literacy course covering operating systems, internet usage, and essential software applications for beginners.",
    likes: "learning computer basics, improving digital skills, becoming tech-savvy",
    duration: '12 Weeks',
    durationType: 'Short Duration',
    category: 'Foundation',
    skills: ['Computer Basics', 'Internet Usage', 'Productivity Software', 'File Management'],
    certification: 'Hartron Computer Fundamentals',
    careerPaths: ['Computer Operator', 'Data Entry Specialist', 'Office Assistant'],
    fee: '₹6,000',
    eligibility: 'No Prerequisites'
  }
];